### PR TITLE
simple 1.19.3 port

### LINKED ISSUE #5: 1.19.2 compatibility?
Your mod seems really good, and so I just wanted to ask if you plan to update it to 1.19.2.

### PR DESCRIPTION
**Pull request by zndrmn**

### CODE REVIEW

**Comment by SilverAndro** [comment]
Uh, none of this seems like changes to the actual mod?

Was this not tested or does the existing version work fine on 1.19.2 already?

**Comment by zndrmn** [comment]
lmao yeah I probably should've tried the original version before I did anything
2.0.4 works fine on 1.19.2

**Comment by SilverAndro** [comment]
Mk, I'll go tag them as compatible and close this then

**Comment by zndrmn** [comment]
hold on, it loads on 2.0.4 but crashes whenever an item with a rarity is on the ground, my fork doesn't crash though

**Comment by SilverAndro** [comment]
Oh wack

**Comment by SilverAndro** [comment]
What's the error like? I wonder if there's some mapping trickery going on

**Comment by zndrmn** [comment]
[crash-2022-11-18_19.51.19-client.txt](https://gist.github.com/zndrmn/5996834cc5ea500168a0cd615fe6a356#file-gistfile1-txt)
[lastest.log](https://gist.github.com/zndrmn/61a63d0e2ed57b86412c9f98ad380630#file-latest-log)

**Comment by SilverAndro** [comment]
Yep seems like it, wack

Guess I'll merge+release once I have a computer again

**Comment by zndrmn** [comment]
alright, I've just got to update the gradle.properties because I made this fork a while ago. also should I test to see if the fork works on 1.16 > 1.19.2? or does that not matter?

**Comment by SilverAndro** [comment]
It won't work, probably 1.19+

**Comment by zndrmn** [comment]
1.19.3 works! only had to replace the old Vec3f for JOML stuff 
and for some reason had to change `TooltipContext.Default.NORMAL` to `TooltipContext.Default.BASIC`

image

**Comment by SilverAndro** [comment]
Awesome thanks! I should have a laptop in just over a week here, let's hope Mojang doesn't drop a major update in that time 😅

**Comment by SilverAndro** [comment]
Uploaded on curseforge and modrinth

**Comment by zndrmn** [comment]
I still have the 1.19.2 version if you want to upload that too

**Comment by SilverAndro** [comment]
Sure, why not

**Comment by zndrmn** [comment]
https://github.com/zndrmn/Lootbeams/releases/tag/2.0.5

**Pull request merged**
